In [6]:
import numpy as np
import pandas as pd

def flash_attention_l1(Q, K, V, B_r, B_c, lam):
    """
    FlashAttention with L1‐distance scoring:
      S_ij[r,c] = -lam * sum_m |Q_i[r,m] - K_j[c,m]|
    
    Args:
        Q, K, V: np arrays of shape (N, d)
        B_r: row block size
        B_c: column block size
        lam: scaling factor for L1 distance

    Returns:
        O: output attention result of shape (N, d)
    """
    N, d = Q.shape
    scale=lam / np.sqrt(d)
    # Initialize outputs & softmax accumulators
    O = np.zeros((N, d), dtype=Q.dtype)
    m = np.full(N, -np.inf, dtype=Q.dtype)
    l = np.zeros(N, dtype=Q.dtype)

    T_r = int(np.ceil(N / B_r))
    T_c = int(np.ceil(N / B_c))

    for j in range(T_c):
        k0, k1 = j * B_c, min((j+1) * B_c, N)
        K_j = K[k0:k1]        # (B_c, d)
        V_j = V[k0:k1]        # (B_c, d)

        for i in range(T_r):
            q0, q1 = i * B_r, min((i+1) * B_r, N)
            Q_i = Q[q0:q1]    # (B_r, d)
            O_i = O[q0:q1]    # (B_r, d)
            m_i = m[q0:q1]    # (B_r,)
            l_i = l[q0:q1]    # (B_r,)

            # 1. Compute L1‐distance based scores (B_r, B_c)
            #    diff has shape (B_r, B_c, d)
            diff = np.abs(Q_i[:, None, :] - K_j[None, :, :])
            S_ij = -scale * np.sum(diff, axis=2)

            # 2. Row‐wise max for numerical stability
            m_tilde = S_ij.max(axis=1)        # (B_r,)

            # 3. Exponentiate shifted scores
            P_tilde = np.exp(S_ij - m_tilde[:, None])  # (B_r, B_c)

            # 4. Row‐sum of exponentials
            l_tilde = P_tilde.sum(axis=1)     # (B_r,)

            # 5. Update running max and sum
            m_new = np.maximum(m_i, m_tilde)
            l_new = (np.exp(m_i - m_new) * l_i) + (np.exp(m_tilde - m_new) * l_tilde)

            # 6. Accumulate partial outputs
            term1 = (np.exp(m_i - m_new) * l_i)[:, None] * O_i                  # (B_r, d)
            term2 = (np.exp(m_tilde - m_new)[:, None]) * (P_tilde @ V_j)        # (B_r, d)
            O_update = (term1 + term2) / l_new[:, None]                         # (B_r, d)

            # Write-back
            O[q0:q1] = O_update
            m[q0:q1] = m_new
            l[q0:q1] = l_new

    return O

# Example usage with 3x3 matrices
Q = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]], dtype=float)

K = Q.copy()
V = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=float)

# Choose block sizes
B_r, B_c = 1, 1

O_fa = flash_attention_l1(Q, K, V, B_r, B_c,1)
O_naive = np.exp(Q @ K.T)
O_naive = (O_naive / np.sum(O_naive, axis=1, keepdims=True)) @ V

# Display results
print("FlashAttention output:\n", O_fa)
print("\nNaive attention output:\n", O_naive)


FlashAttention output:
 [[2.74 3.74 4.74]
 [4.   5.   6.  ]
 [5.26 6.26 7.26]]

Naive attention output:
 [[2.907 3.907 4.907]
 [4.    5.    6.   ]
 [5.093 6.093 7.093]]


In [7]:
def pretty_print(arr: np.ndarray,
                 name: str = None,
                 precision: int = 3,
                 suppress: bool = True):
    """
    Nicely print any NumPy array:
      - 1-D → as a single-column DataFrame
      - 2-D → as a DataFrame
      - ND (N>2) → iterate slices on axis-0
    
    Args:
        arr:       the array to print
        name:      optional name/title
        precision: decimal places for floats
        suppress:  suppress small values (numpy.set_printoptions)
    """
    # configure numpy prints
    np.set_printoptions(precision=precision, suppress=suppress)
    
    if name is not None:
        print(f"\n=== {name} ===")
    
    ndim = arr.ndim
    if ndim == 0:
        # scalar
        print(arr.item())
    elif ndim == 1:
        # vector
        df = pd.DataFrame(arr, columns=["value"])
        print(df)
    elif ndim == 2:
        # matrix
        df = pd.DataFrame(arr)
        print(df)
    else:
        # ND: iterate over first axis
        for idx in range(arr.shape[0]):
            slice_name = f"{name+' ' if name else ''}slice[{idx}]"
            pretty_print(arr[idx], name=slice_name,
                         precision=precision, suppress=suppress)

FLASHATTENTION 2

In [8]:
import numpy as np
import math

def adder_tree_levels(arr: np.ndarray):
    """
    Simulate an adder tree over a 1D array `arr`.
    Returns a list of numpy arrays: level 0 is the inputs,
    level 1 is pairwise sums (with an odd leftover copied forward), ...
    until a single scalar remains.
    """
    levels = [arr.copy()]
    cur = arr.copy()
    while cur.size > 1:
        next_level = []
        i = 0
        while i < cur.size:
            if i + 1 < cur.size:
                next_level.append(cur[i] + cur[i + 1])
                i += 2
            else:
                # odd element: carry forward unchanged
                next_level.append(cur[i])
                i += 1
        cur = np.array(next_level, dtype=arr.dtype)
        levels.append(cur.copy())
    return levels

In [9]:
def flash_attention2(Q: np.ndarray, K: np.ndarray, V: np.ndarray,
                     block_rows: int, block_cols: int, lam=1.0):
    """
    FlashAttention-2 forward pass in NumPy with adder-tree printing for the
    per-row sum used to compute S.

    Args:
        Q: Queries, shape (N, D)
        K: Keys,    shape (N, D)
        V: Values,  shape (N, D_v)
        block_rows: Block size for Q (B_r)
        block_cols: Block size for K, V (B_c)
        lam: scaling multiplier
    Returns:
        O: Output, shape (N, D_v)
    """
    N, D = Q.shape
    _, D_v = V.shape

    # Number of tiles
    T_r = math.ceil(N / block_rows)
    T_c = math.ceil(N / block_cols)

    O = np.zeros((N, D_v), dtype=Q.dtype)
    L = np.zeros(N, dtype=Q.dtype)

    scale = lam / np.sqrt(D)

    for i in range(T_r):
        start_r = i * block_rows
        end_r = min((i + 1) * block_rows, N)
        Qi = Q[start_r:end_r]                     # (B_r_i, D)
        B_r_i = Qi.shape[0]

        # Initialize online-softmax accumulators
        m = np.full(B_r_i, -np.inf, dtype=Q.dtype)  # running max
        l = np.zeros(B_r_i, dtype=Q.dtype)          # running sum exp
        O_tilde = np.zeros((B_r_i, D_v), dtype=Q.dtype)
        print("Qi\n", Qi)

        for j in range(T_c):
            start_c = j * block_cols
            end_c = min((j + 1) * block_cols, N)
            Kj = K[start_c:end_c]                 # (B_c_j, D)
            Vj = V[start_c:end_c]                 # (B_c_j, D_v)

            pretty_print(Kj, "Kj")
            pretty_print(Vj, "Vj")

            # 1) Raw elementwise absolute differences
            diff = np.abs(Qi[:, None, :] - Kj[None, :, :])  # (B_r_i, B_c_j, D)
            print("Sub")
            pretty_print(Qi[:, None, :], "Q")
            print("-")
            pretty_print(Kj[None, :, :], "K")
            print("=")
            pretty_print(diff, "Diff")

            # --- ADDED: compute sum across D with an adder-tree for each (row, col)
            # We'll build S by running an adder tree on diff[r, c, :].
            Bc_j = diff.shape[1]
            S = np.zeros((B_r_i, Bc_j), dtype=Q.dtype)
            for r_idx in range(B_r_i):
                for c_idx in range(Bc_j):
                    vec = diff[r_idx, c_idx, :]
                    levels = adder_tree_levels(vec)
                    # Print the adder-tree intermediate levels
                    print(f"Adder-tree for Qi row {start_r + r_idx} vs Kj row {start_c + c_idx}:")
                    for lvl_idx, lvl in enumerate(levels):
                        print(f"  level {lvl_idx} (size {lvl.size}): {lvl}")
                    final_sum = levels[-1][0]
                    print(f"  -> final sum = {final_sum}\n")
                    S[r_idx, c_idx] = -scale * final_sum

            pretty_print(S, "S (computed via adder-tree)")

            # 2) Update running max
            row_max = np.max(S, axis=1)            # (B_r_i,)
            new_m = np.maximum(m, row_max)
            pretty_print(m, "m")
            pretty_print(row_max, "row_max")
            pretty_print(new_m, "new_m")
            # 3) Compute shifted exp
            eS = np.exp(S)
            e_neg_new_m = np.exp(-new_m)  # shape (B_r_i,)

            pretty_print(eS, "exp(S)")
            pretty_print(e_neg_new_m, "exp(-new_m)")

            P = eS * e_neg_new_m[:, None]        # (B_r_i, B_c_j)
            pretty_print(P, "P")

            # 4) Update running sum of exp
            sum_P = np.zeros(B_r_i, dtype=Q.dtype)
            for r_idx in range(B_r_i):
                vec = P[r_idx, :]
                levels = adder_tree_levels(vec)
                print(f"Adder-tree for sum_P of row {start_r + r_idx}:")
                for lvl_idx, lvl in enumerate(levels):
                    print(f"  level {lvl_idx} (size {lvl.size}): {lvl}")
                final_sum = levels[-1][0]
                print(f"  -> sum_P[{r_idx}] = {final_sum}\n")
                sum_P[r_idx] = final_sum

            pretty_print(sum_P, "sum_P (via adder-tree)")

            # 4) Update running sum of exp using the adder-tree sum
            l = np.exp(m - new_m) * l + sum_P
            pretty_print(l, "l")

            # 5) Accumulate unnormalized output
            O_tilde = (np.exp(m - new_m)[:, None] * O_tilde) + (P @ Vj)
            pretty_print(O_tilde, "O_tilde")

            # Commit new max
            m = new_m
            print("-" * 90)

        # 6) Final normalization for this block
        O[start_r:end_r] = O_tilde / l[:, None]
        L[start_r:end_r] = m + np.log(l)

    return O

In [10]:
import numpy as np

# --- Parameters (match your SV testbench) ---
Br = 4      # number of Q rows you filled in SV (change as needed)
Bc = 4      # number of K/V rows you filled in SV (change as needed)
D  = 16      # dimension D (number of lanes in your row-major parallel load)
lam = 1.0   # scale multiplier used by flash_attention2

# Create full arrays with N = max(Br, Bc)
N = max(Br, Bc)
Q = np.zeros((N, D), dtype=float)
K = np.zeros((N, D), dtype=float)
V = np.zeros((N, D), dtype=float)   # V has same D in your SV snippet

# Fill according to your SystemVerilog formulas:
# Qmat[i][j] = i + j * 0.1
# Kmat[i][j] = i * 2 + j * 0.2
# Vmat[i][j] = i * 3 + j * 0.3
for i in range(Br):
    for j in range(D):
        Q[i, j] = i + j * 0.1

for i in range(Bc):
    for j in range(D):
        K[i, j] = i * 2 + j * 0.2
        V[i, j] = i * 3 + j * 0.3

# (Rows i >= Br or i >= Bc remain zero — matches zero-padding in your SV pack.)

# Optional: print the matrices to confirm
print("Q:\n", Q)
print("K:\n", K)
print("V:\n", V)

# --- Call flash_attention2 ---
# Assumes flash_attention2(Q, K, V, block_rows, block_cols, lam) is defined in the same module
res = flash_attention2(Q, K, V, block_rows=Br, block_cols=Bc, lam=lam)


Q:
 [[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5]]
K:
 [[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3. ]
 [2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4 4.6 4.8 5. ]
 [4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7. ]
 [6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9. ]]
V:
 [[ 0.   0.3  0.6  0.9  1.2  1.5  1.8  2.1  2.4  2.7  3.   3.3  3.6  3.9
   4.2  4.5]
 [ 3.   3.3  3.6  3.9  4.2  4.5  4.8  5.1  5.4  5.7  6.   6.3  6.6  6.9
   7.2  7.5]
 [ 6.   6.3  6.6  6.9  7.2  7.5  7.8  8.1  8.4  8.7  9.   9.3  9.6  9.9
  10.2 10.5]
 [ 9.   9.3  9.6  9.9 10.2 10.5 10.8 11.1 11.4 11.7 12.  12.3 12.6 12.9
  13.2 13.5]]
Qi
 [[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 